# Generated by Django 4.2.26 on 2025-11-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='salt',
        ),
    ]
