# Generated by Django 4.2.26 on 2025-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
